GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiBkdWUiLCJpYXQiOjE3MTUyODI0MzksImV4cCI6MTcxNTI4NjAzOX0.rtXYG3ccP_J2oPzdBlINgmUoR1rAsnIK8objBUxtc94

### Create Product
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiBkdWUiLCJpYXQiOjE3MTUyODI3OTcsImV4cCI6MTcxNTI4NjM5N30.28KjByD5nSAjOBJ3q9kpTg0gdjLWvTqVhYJmtlZUU6A

{
    "name": "Product 1",
    "description": "Product 1 description",
    "image_url": "https://www.foto.foto/fototeste",
    "price": 100 
}

###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiBkdWUiLCJpYXQiOjE3MTUyODMxNzQsImV4cCI6MTcxNTI5Mzk3NH0.HUl2WoEse-in6cb1l7cNgoiPlu3uEFZWPoo0W3QOf8o
###
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiBkdWUiLCJpYXQiOjE3MTUyODMxNzQsImV4cCI6MTcxNTI5Mzk3NH0.HUl2WoEse-in6cb1l7cNgoiPlu3uEFZWPoo0W3QOf8o

{
    "items": [
        {
            "product_id": "8e3c7e-2c11-4f77-8c83-08ac57f786de",
            "quantity": 1 
        },
        {
            "product_id": "d49de2-a782-4986-af8c-2e986c17abba",
            "quantity": 1 
        }
    ],
    "card_hash": "123"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "john due",
    "password": "john due"
}